# Generated by Django 5.0.2 on 2024-02-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppBlog', '0002_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fkPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='myAppBlog.post'),
        ),
    ]
