# Generated by Django 5.0.2 on 2024-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppBlog', '0003_alter_comentarios_fkpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
